/**
 * The console's receipt bytes against the engine's.
 *
 * A receipt frozen in the browser and verified by the engine is one hash or it
 * is nothing. The eleven payloads in the fixture are chosen for the places the
 * two serialisers actually differ — unicode, escapes, the solidus, floats that
 * round-trip, exponents, signed zero, empty containers and key order — and the
 * engine's exact bytes are generated by
 * `scripts/validation/export_endpoints.py`.
 */
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";

import { loadTs } from "./helpers/load-ts.mjs";

const fixture = JSON.parse(
  readFileSync(join(import.meta.dirname, "fixtures", "canonical-bytes.json"), "utf8"),
);
const { canonicalBytes, receiptHash, buildReceipt, ReceiptError } = loadTs(
  "lib/validation/receipt.ts",
);

test("every engine payload serialises to the same bytes in the console", () => {
  assert.equal(fixture.cases.length, fixture.n_cases);
  assert.ok(fixture.n_cases >= 11);
  const wrong = [];
  for (const kase of fixture.cases) {
    const mine = canonicalBytes(kase.payload);
    if (mine !== kase.bytes) {
      wrong.push({ payload: kase.payload, engine: kase.bytes, console: mine });
    }
  }
  assert.deepEqual(wrong, []);
});

test("and therefore to the same sha256", () => {
  for (const kase of fixture.cases) {
    assert.equal(
      receiptHash(kase.payload),
      kase.sha256,
      `hash differs for ${JSON.stringify(kase.payload).slice(0, 60)}`,
    );
  }
});

test("the hash is the digest of exactly those bytes", () => {
  // Belt and braces: the fixture's own sha256 against Node's OpenSSL, so a bug
  // in the browser digest cannot hide behind a bug in the generator.
  for (const kase of fixture.cases) {
    assert.equal(createHash("sha256").update(kase.bytes, "utf8").digest("hex"), kase.sha256);
  }
});

test("a non-finite number is refused rather than written", () => {
  for (const value of [NaN, Infinity, -Infinity]) {
    assert.throws(() => canonicalBytes({ x: value }), ReceiptError);
  }
});

test("a receipt cannot be made to carry an outcome", () => {
  const base = {
    roundId: "r1",
    createdUtc: "2026-10-03T12:00:00+00:00",
    screen: { screen_id: "s1" },
    candidates: [{ gene: "CDK2", rank: 1, score: 0.9, probability: null, question: "reproduces", evidence: {} }],
    validationSet: { slots: [] },
    rankings: {},
    model: {},
    calibration: null,
    coverage: {},
    endpoint: null,
    laboratoryThreshold: null,
    provenance: {},
  };
  assert.doesNotThrow(() => buildReceipt(base));
  for (const evidence of [{ result: "validated" }, { nested: { ground_truth: 1 } }]) {
    assert.throws(
      () =>
        buildReceipt({
          ...base,
          candidates: [{ ...base.candidates[0], evidence }],
        }),
      /looks like an outcome/,
    );
  }
});

test("a receipt freezes the whole universe, with no gene twice", () => {
  const base = {
    roundId: "r1",
    createdUtc: "2026-10-03T12:00:00+00:00",
    screen: {},
    candidates: [],
    validationSet: {},
    rankings: {},
    model: {},
    calibration: null,
    coverage: {},
    endpoint: null,
    laboratoryThreshold: null,
    provenance: {},
  };
  assert.throws(() => buildReceipt(base), /candidate universe/);
  assert.throws(
    () =>
      buildReceipt({
        ...base,
        candidates: [
          { gene: "A", rank: 1, score: null, probability: null, question: null, evidence: {} },
          { gene: "A", rank: 2, score: null, probability: null, question: null, evidence: {} },
        ],
      }),
    /same gene twice/,
  );
});

test("the payload says its timestamp is not trusted", () => {
  const built = buildReceipt({
    roundId: "r1",
    createdUtc: "2026-10-03T12:00:00+00:00",
    screen: {},
    candidates: [{ gene: "A", rank: 1, score: null, probability: null, question: null, evidence: {} }],
    validationSet: {},
    rankings: {},
    model: {},
    calibration: null,
    coverage: {},
    endpoint: null,
    laboratoryThreshold: null,
    provenance: {},
  });
  assert.match(String(built.payload.timestamp_trust), /independent custodian/);
  assert.match(built.sha256, /^[0-9a-f]{64}$/);
  assert.ok(built.bytes.endsWith("\n"));
});
