"use client";
import { useState } from "react";
import type { IntakeSample } from "@/lib/intake/shape";
import { parseTranscriptExpression, validateLabOptions, type LabOptions } from "@/lib/lab/options";
export function LabEvidenceSettings({ value, samples, expressionFiles = [], deterministicOnly, onChange, onDeterministic }: { value: LabOptions; samples: IntakeSample[]; expressionFiles?: { id: string; name: string }[]; deterministicOnly: boolean; onChange: (value: LabOptions) => void; onDeterministic: (value: boolean) => void }) {
  const [error, setError] = useState<string | null>(null);
  const chosen = samples.filter(s => s.included !== false);
  const update = (patch: Partial<LabOptions>) => onChange({ ...value, ...patch });
  const field = "rounded border border-line bg-white px-2 py-1 text-xs text-ink";
  const problem = validateLabOptions(value, chosen.map(s => s.label));
  return <details className="rounded-lg border border-line bg-canvas p-3"><summary className="cursor-pointer text-sm font-medium text-ink">Laboratory evidence modules</summary><div className="mt-4 space-y-4 text-xs">
    <label className="flex items-center gap-2"><input type="checkbox" checked={deterministicOnly} onChange={e => onDeterministic(e.target.checked)} /> Deterministic analysis only , do not execute predictive models</label>
    <p className="leading-relaxed text-muted">All modules retain the original statistics and record their source and exact settings. Library diagnostics are included automatically. Reference context and fitted trends are not experimental validation.</p>
    <label className="flex items-center gap-2"><input type="checkbox" checked={!!value.isoforms} onChange={e => update({ isoforms: e.target.checked, ...(!e.target.checked ? { transcript_expression: undefined, expression_source: undefined, transcript_expression_file_id: undefined } : {}) })} /> Map guides across human GRCh38 coding transcripts , knockout only</label>
    {value.isoforms && <div className="space-y-2"><label className="block">Use an uploaded transcript-expression file (JSON or transcript_id / TPM TSV, up to 100 MB)<select className={`${field} mt-1 block w-full`} value={value.transcript_expression_file_id ?? ""} onChange={e => update({ transcript_expression_file_id: e.target.value || undefined, transcript_expression: undefined, expression_source: expressionFiles.find(f => f.id === e.target.value)?.name })}><option value="">Annotation only, or inline import below</option>{expressionFiles.map(f => <option key={f.id} value={f.id}>{f.name}</option>)}</select></label><p className="text-muted">Upload larger measured expression files with the experiment, then select them here. Their original bytes and SHA-256 are preserved. A gene-level RNA matrix cannot stand in for transcript measurements.</p><label className="block">Optional measured transcript expression (JSON or two-column transcript_id / TPM TSV)<input type="file" accept=".json,.tsv,.txt" className="mt-1 block" onChange={async e => { const file = e.target.files?.[0]; if (!file) return; try { if (file.size > 1024 * 1024) throw new Error("Transcript expression exceeds the 1 MB inline import limit; attach larger measured matrices as workspace evidence and select a gene subset for this inline mapping."); const expression = parseTranscriptExpression(await file.text()); update({ transcript_expression: expression, expression_source: file.name, transcript_expression_file_id: undefined }); setError(null); } catch (failure) { setError(failure instanceof Error ? failure.message : "Could not parse expression."); } }} /></label>{value.transcript_expression && <><p>{Object.keys(value.transcript_expression).length} transcript measurements , missing IDs remain unknown. Use annotation transcript IDs exactly; version suffixes are not silently merged.</p><label className="block">Measurement source / sample<input className={`${field} ml-2 w-64`} value={value.expression_source ?? ""} onChange={e => update({ expression_source: e.target.value })} /></label><button type="button" className="underline" onClick={() => update({ transcript_expression: undefined, expression_source: undefined, transcript_expression_file_id: undefined })}>Remove expression measurements</button></>}</div>}
    <label className="flex items-center gap-2"><input type="checkbox" checked={!!value.context} onChange={e => update({ context: e.target.checked })} /> DepMap validation context matrix (human cancer models)</label>
    {value.context && <label className="block">Pinned gene-effect release<select className={`${field} ml-2`} value={value.depmap_release ?? "24Q4"} onChange={e => update({ depmap_release: e.target.value as LabOptions["depmap_release"] })}><option value="24Q4">24Q4 , complete local reference</option><option value="26Q1">26Q1 , gene effects, with 24Q4 metadata/CN labelled separately</option></select></label>}
    <label className="flex items-center gap-2"><input type="checkbox" checked={!!value.time_course?.length} onChange={e => update({ time_course: e.target.checked ? chosen.map(s => ({ sample: s.label, day: 0, replicate: String(s.replicate), condition: s.role })) : [] })} /> Fit temporal guide-abundance kinetics , at least 3 times per biological trajectory</label>
    {!!value.time_course?.length && <div className="space-y-3"><p className="text-muted">Declare elapsed days from the same origin, condition and biological trajectory. Repeated samples from one culture share a trajectory. Distinct trajectory labels must represent independent biological replicates.</p><div className="overflow-auto"><table className="w-full text-left"><thead><tr>{["Sample", "Days", "Biological trajectory", "Condition", "Include"].map(h => <th key={h} className="p-1">{h}</th>)}</tr></thead><tbody>{chosen.map(sample => {
      const point = value.time_course?.find(p => p.sample === sample.label);
      const change = (patch: Partial<NonNullable<LabOptions["time_course"]>[number]>) => update({ time_course: value.time_course?.map(p => p.sample === sample.label ? { ...p, ...patch } : p) });
      return <tr key={sample.label}><th className="p-1 font-normal">{sample.label}</th><td><input aria-label={`${sample.label} elapsed days`} className={`${field} w-20`} disabled={!point} type="number" min={0} step="any" value={point?.day ?? 0} onChange={e => change({ day: Number(e.target.value) })} /></td><td><input aria-label={`${sample.label} biological trajectory`} disabled={!point} className={`${field} w-28`} value={point?.replicate ?? ""} onChange={e => change({ replicate: e.target.value })} /></td><td><input aria-label={`${sample.label} condition`} disabled={!point} className={`${field} w-28`} value={point?.condition ?? ""} onChange={e => change({ condition: e.target.value })} /></td><td><input aria-label={`Include ${sample.label} in kinetics`} type="checkbox" checked={!!point} onChange={e => update({ time_course: e.target.checked ? [...(value.time_course ?? []), { sample: sample.label, day: 0, replicate: String(sample.replicate), condition: sample.role }] : value.time_course?.filter(p => p.sample !== sample.label) })} /></td></tr>;
    })}</tbody></table></div><label>Normalization<select className={`${field} ml-2`} value={value.kinetic_normalization ?? "median"} onChange={e => update({ kinetic_normalization: e.target.value as "median" | "control" })}><option value="median">Median ratios , common positive guides</option><option value="control">Negative-control guide median ratios</option></select></label><label className="ml-3">Pseudocount<input className={`${field} ml-2 w-20`} type="number" min={0.000001} step="any" value={value.pseudocount ?? 1} onChange={e => update({ pseudocount: Number(e.target.value) })} /></label></div>}
    <label className="block">Reagent / library lot (optional)<input className={`${field} ml-2 w-64`} maxLength={200} value={value.reagent_lot ?? ""} onChange={e => update({ reagent_lot: e.target.value })} /></label>
    {(error || problem) && <p role="alert" className="text-orange-700">{error ?? problem}</p>}
  </div></details>;
}
