/**
 * TxScore TypeScript Client
 * 
 * Comprehensive SDK for Therapeutic Viability Score (TxScore) database
 * 
 * Features:
 * - Type-safe Supabase queries
 * - TxScore computation utilities
 * - Advanced filtering and ranking
 * - Batch operations
 * - Cache management
 * 
 * @version 1.0.0
 * @author SplicR Team
 */

import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './database.types'; // Generated by Supabase CLI

// =====================================================================
// TYPE DEFINITIONS
// =====================================================================

export interface Gene {
  gene_id: string;
  gene_symbol: string;
  uniprot_id?: string | null;
  gene_name?: string | null;
  chromosome?: string | null;
  start_position?: number | null;
  end_position?: number | null;
  strand?: string | null;
  aliases?: Record<string, any> | null;
  gene_type?: string | null;
  gene_biotype?: string | null;
  description?: string | null;
  protein_length?: number | null;
  protein_class?: string | null;
  protein_family?: string | null;
  updated_at?: string;
}

export interface DepMapData {
  gene_id: string;
  cell_line_id: string;
  chronos_effect: number;
  dependency_probability?: number | null;
  cancer_type?: string | null;
  tissue_origin?: string | null;
  depmap_release: string;
}

export interface GTExExpression {
  gene_id: string;
  tissue_name: string;
  median_tpm: number;
  mean_tpm?: number | null;
  std_tpm?: number | null;
  samples_count: number;
}

export interface GnomADConstraint {
  gene_id: string;
  loeuf?: number | null;
  loeuf_lower?: number | null;
  loeuf_upper?: number | null;
  pli?: number | null;
  mis_z?: number | null;
  oe_lof?: number | null;
  obs_lof?: number | null;
  exp_lof?: number | null;
}

export interface AlphaFoldStructure {
  gene_id: string;
  uniprot_id: string;
  mean_plddt: number;
  max_plddt?: number | null;
  min_plddt?: number | null;
  structure_url?: string | null;
  pockets?: BindingPocket[] | null;
  num_druggable_pockets?: number | null;
  domains?: Domain[] | null;
  disordered_regions?: DisorderedRegion[] | null;
  disorder_fraction?: number | null;
}

export interface BindingPocket {
  id: number;
  volume: number;
  druggability_score: number;
  residues: string[];
  center: { x: number; y: number; z: number };
}

export interface Domain {
  name: string;
  pfam_id?: string | null;
  interpro_id?: string | null;
  start: number;
  end: number;
  description?: string | null;
}

export interface DisorderedRegion {
  start: number;
  end: number;
  score: number;
}

export interface ClinVarVariant {
  variant_id: string;
  gene_id: string;
  clinical_significance: string;
  review_status?: string | null;
  variant_type?: string | null;
  molecular_consequence?: string | null;
  chromosome: string;
  position: number;
  hgvs_c?: string | null;
  hgvs_p?: string | null;
  conditions?: string[] | null;
}

export interface DrugInteraction {
  gene_id: string;
  drug_name: string;
  drug_chembl_id?: string | null;
  drug_drugbank_id?: string | null;
  interaction_type?: string | null;
  approval_status?: string | null;
  clinical_trial_phase?: string | null;
  mechanism_of_action?: string | null;
  source: string;
}

export interface ClinicalTrial {
  nct_id: string;
  gene_id: string;
  title: string;
  phase?: string | null;
  status: string;
  start_date?: string | null;
  completion_date?: string | null;
  enrollment?: number | null;
  conditions?: string[] | null;
  interventions?: Intervention[] | null;
}

export interface Intervention {
  type: string;
  name: string;
  description?: string | null;
}

export interface TxScore {
  gene_id: string;
  cancer_type: string;
  tvs: number;
  efficacy_score: number;
  safety_score: number;
  druggability_score: number;
  precedent_score: number;
  stratification_score: number;
  efficacy_components?: any;
  tissue_risks?: any;
  critical_tissue_risk?: number | null;
  modality_recommendation?: ModalityRecommendation | null;
  precedent_components?: any;
  biomarker_features?: BiomarkerFeature[] | null;
  computed_at?: string;
  expires_at?: string | null;
}

export interface ModalityRecommendation {
  small_molecule: number;
  antibody: number;
  gene_therapy: number;
  recommended_modality: 'small_molecule' | 'antibody' | 'gene_therapy';
}

export interface BiomarkerFeature {
  feature_type: string;
  feature_name: string;
  correlation: number;
  prevalence: number;
}

export interface TxScoreFilters {
  cancer_type?: string;
  min_tvs?: number;
  min_efficacy?: number;
  min_safety?: number;
  min_druggability?: number;
  protein_class?: string;
  has_approved_drugs?: boolean;
  has_clinical_trials?: boolean;
  recommended_modality?: 'small_molecule' | 'antibody' | 'gene_therapy';
  gene_ids?: string[];
}

export interface RankingOptions {
  limit?: number;
  offset?: number;
  order_by?: 'tvs' | 'efficacy_score' | 'safety_score' | 'druggability_score';
  order_direction?: 'asc' | 'desc';
}

// =====================================================================
// TXSCORE CLIENT CLASS
// =====================================================================

export class TxScoreClient {
  private supabase: SupabaseClient<Database>;

  constructor(supabaseUrl: string, supabaseKey: string) {
    this.supabase = createClient<Database>(supabaseUrl, supabaseKey);
  }

  // ===================================================================
  // GENE QUERIES
  // ===================================================================

  /**
   * Get gene by Ensembl ID
   */
  async getGene(geneId: string): Promise<Gene | null> {
    const { data, error } = await this.supabase
      .from('tx_genes_master')
      .select('*')
      .eq('gene_id', geneId)
      .single();

    if (error) throw error;
    return data as Gene | null;
  }

  /**
   * Get gene by symbol (case-insensitive)
   */
  async getGeneBySymbol(symbol: string): Promise<Gene | null> {
    const { data, error } = await this.supabase
      .from('tx_genes_master')
      .select('*')
      .ilike('gene_symbol', symbol)
      .single();

    if (error) throw error;
    return data as Gene | null;
  }

  /**
   * Search genes by symbol or name (fuzzy matching)
   */
  async searchGenes(query: string, limit: number = 20): Promise<Gene[]> {
    const { data, error } = await this.supabase
      .from('tx_genes_master')
      .select('*')
      .or(`gene_symbol.ilike.%${query}%,gene_name.ilike.%${query}%`)
      .limit(limit);

    if (error) throw error;
    return (data || []) as Gene[];
  }

  /**
   * Get genes by protein class
   */
  async getGenesByProteinClass(proteinClass: string): Promise<Gene[]> {
    const { data, error } = await this.supabase
      .from('tx_genes_master')
      .select('*')
      .eq('protein_class', proteinClass);

    if (error) throw error;
    return (data || []) as Gene[];
  }

  /**
   * Get genes in genomic region
   */
  async getGenesInRegion(
    chromosome: string,
    start: number,
    end: number
  ): Promise<Gene[]> {
    const { data, error } = await this.supabase
      .from('tx_genes_master')
      .select('*')
      .eq('chromosome', chromosome)
      .gte('start_position', start)
      .lte('end_position', end);

    if (error) throw error;
    return (data || []) as Gene[];
  }

  // ===================================================================
  // DEPMAP QUERIES
  // ===================================================================

  /**
   * Get DepMap data for a gene
   */
  async getDepMapData(
    geneId: string,
    cancerType?: string,
    release?: string
  ): Promise<DepMapData[]> {
    let query = this.supabase
      .from('tx_depmap_data')
      .select('*')
      .eq('gene_id', geneId);

    if (cancerType) {
      query = query.eq('cancer_type', cancerType);
    }

    if (release) {
      query = query.eq('depmap_release', release);
    }

    const { data, error } = await query;

    if (error) throw error;
    return (data || []) as DepMapData[];
  }

  /**
   * Get essential genes for a cancer type
   * (Chronos < -0.75 in >50% of cell lines)
   */
  async getEssentialGenes(
    cancerType: string,
    chronosThreshold: number = -0.75,
    prevalenceThreshold: number = 0.5
  ): Promise<string[]> {
    const { data, error } = await this.supabase.rpc('get_essential_genes' as any, {
      p_cancer_type: cancerType,
      p_chronos_threshold: chronosThreshold,
      p_prevalence_threshold: prevalenceThreshold,
    });

    if (error) throw error;
    return (data || []) as string[];
  }

  /**
   * Compute selectivity index for a gene
   */
  async getSelectivityIndex(
    geneId: string,
    targetCancerType: string
  ): Promise<number> {
    const { data, error } = await this.supabase.rpc('compute_selectivity_index' as any, {
      p_gene_id: geneId,
      p_cancer_type: targetCancerType,
    });

    if (error) throw error;
    return (data as number) || 0;
  }

  // ===================================================================
  // GTEX QUERIES
  // ===================================================================

  /**
   * Get GTEx expression for a gene
   */
  async getGTExExpression(geneId: string): Promise<GTExExpression[]> {
    const { data, error } = await this.supabase
      .from('tx_gtex_expression')
      .select('*')
      .eq('gene_id', geneId)
      .order('median_tpm', { ascending: false });

    if (error) throw error;
    return (data || []) as GTExExpression[];
  }

  /**
   * Get highly expressed tissues for a gene (TPM > threshold)
   */
  async getHighExpressionTissues(
    geneId: string,
    tpmThreshold: number = 10
  ): Promise<string[]> {
    const { data, error } = await this.supabase
      .from('tx_gtex_expression')
      .select('tissue_name')
      .eq('gene_id', geneId)
      .gt('median_tpm', tpmThreshold)
      .order('median_tpm', { ascending: false });

    if (error) throw error;
    return data?.map((d) => d.tissue_name) || [];
  }

  /**
   * Get tissue-specific expression profile
   */
  async getTissueExpression(
    geneId: string,
    tissueName: string
  ): Promise<GTExExpression | null> {
    const { data, error } = await this.supabase
      .from('tx_gtex_expression')
      .select('*')
      .eq('gene_id', geneId)
      .eq('tissue_name', tissueName)
      .single();

    if (error) throw error;
    return data as GTExExpression | null;
  }

  // ===================================================================
  // GNOMAD CONSTRAINT QUERIES
  // ===================================================================

  /**
   * Get gnomAD constraint for a gene
   */
  async getGnomADConstraint(geneId: string): Promise<GnomADConstraint | null> {
    const { data, error } = await this.supabase
      .from('tx_gnomad_constraint')
      .select('*')
      .eq('gene_id', geneId)
      .single();

    if (error) throw error;
    return data as GnomADConstraint | null;
  }

  /**
   * Get constrained genes (LOEUF < threshold OR pLI > threshold)
   */
  async getConstrainedGenes(
    loeufThreshold: number = 0.6,
    pliThreshold: number = 0.9
  ): Promise<string[]> {
    const { data, error } = await this.supabase
      .from('tx_gnomad_constraint')
      .select('gene_id')
      .or(`loeuf.lt.${loeufThreshold},pli.gt.${pliThreshold}`);

    if (error) throw error;
    return data?.map((d) => d.gene_id) || [];
  }

  // ===================================================================
  // ALPHAFOLD STRUCTURE QUERIES
  // ===================================================================

  /**
   * Get AlphaFold structure for a gene
   */
  async getAlphaFoldStructure(geneId: string): Promise<AlphaFoldStructure | null> {
    const { data, error } = await this.supabase
      .from('tx_alphafold_structures')
      .select('*')
      .eq('gene_id', geneId)
      .single();

    if (error) throw error;
    return data as AlphaFoldStructure | null;
  }

  /**
   * Get genes with high-quality structures (pLDDT > threshold)
   */
  async getHighQualityStructures(
    pLDDTThreshold: number = 70
  ): Promise<string[]> {
    const { data, error } = await this.supabase
      .from('tx_alphafold_structures')
      .select('gene_id')
      .gt('mean_plddt', pLDDTThreshold);

    if (error) throw error;
    return data?.map((d) => d.gene_id) || [];
  }

  /**
   * Get genes with druggable pockets
   */
  async getGenesWithDruggablePockets(minPockets: number = 1): Promise<string[]> {
    const { data, error } = await this.supabase
      .from('tx_alphafold_structures')
      .select('gene_id')
      .gte('num_druggable_pockets', minPockets);

    if (error) throw error;
    return data?.map((d) => d.gene_id) || [];
  }

  // ===================================================================
  // CLINVAR QUERIES
  // ===================================================================

  /**
   * Get ClinVar variants for a gene
   */
  async getClinVarVariants(geneId: string): Promise<ClinVarVariant[]> {
    const { data, error } = await this.supabase
      .from('tx_clinvar_variants')
      .select('*')
      .eq('gene_id', geneId);

    if (error) throw error;
    return (data || []) as ClinVarVariant[];
  }

  /**
   * Get pathogenic variants for a gene
   */
  async getPathogenicVariants(geneId: string): Promise<ClinVarVariant[]> {
    const { data, error } = await this.supabase
      .from('tx_clinvar_variants')
      .select('*')
      .eq('gene_id', geneId)
      .in('clinical_significance', ['Pathogenic', 'Likely pathogenic']);

    if (error) throw error;
    return (data || []) as ClinVarVariant[];
  }

  // ===================================================================
  // DRUG INTERACTION QUERIES
  // ===================================================================

  /**
   * Get drug interactions for a gene
   */
  async getDrugInteractions(geneId: string): Promise<DrugInteraction[]> {
    const { data, error } = await this.supabase
      .from('tx_drug_interactions')
      .select('*')
      .eq('gene_id', geneId);

    if (error) throw error;
    return (data || []) as DrugInteraction[];
  }

  /**
   * Get approved drugs for a gene
   */
  async getApprovedDrugs(geneId: string): Promise<DrugInteraction[]> {
    const { data, error } = await this.supabase
      .from('tx_drug_interactions')
      .select('*')
      .eq('gene_id', geneId)
      .eq('approval_status', 'approved');

    if (error) throw error;
    return (data || []) as DrugInteraction[];
  }

  /**
   * Get genes with approved drugs
   */
  async getGenesWithApprovedDrugs(): Promise<string[]> {
    const { data, error } = await this.supabase
      .from('tx_drug_interactions')
      .select('gene_id')
      .eq('approval_status', 'approved');

    if (error) throw error;
    return [...new Set(data?.map((d) => d.gene_id) || [])];
  }

  // ===================================================================
  // CLINICAL TRIAL QUERIES
  // ===================================================================

  /**
   * Get clinical trials for a gene
   */
  async getClinicalTrials(geneId: string): Promise<ClinicalTrial[]> {
    const { data, error } = await this.supabase
      .from('tx_clinical_trials')
      .select('*')
      .eq('gene_id', geneId);

    if (error) throw error;
    return (data || []) as ClinicalTrial[];
  }

  /**
   * Get advanced-stage trials (Phase 2/3)
   */
  async getAdvancedTrials(geneId: string): Promise<ClinicalTrial[]> {
    const { data, error } = await this.supabase
      .from('tx_clinical_trials')
      .select('*')
      .eq('gene_id', geneId)
      .in('phase', ['Phase 2', 'Phase 3', 'Phase 4']);

    if (error) throw error;
    return (data || []) as ClinicalTrial[];
  }

  /**
   * Get failed trials (Terminated/Withdrawn in Phase 2/3)
   */
  async getFailedTrials(geneId: string): Promise<ClinicalTrial[]> {
    const { data, error } = await this.supabase
      .from('tx_clinical_trials')
      .select('*')
      .eq('gene_id', geneId)
      .in('status', ['Terminated', 'Withdrawn'])
      .in('phase', ['Phase 2', 'Phase 3']);

    if (error) throw error;
    return (data || []) as ClinicalTrial[];
  }

  // ===================================================================
  // TXSCORE QUERIES
  // ===================================================================

  /**
   * Get TxScore for a gene and cancer type
   */
  async getTxScore(geneId: string, cancerType: string): Promise<TxScore | null> {
    const { data, error } = await this.supabase
      .from('tx_txscore_cache')
      .select('*')
      .eq('gene_id', geneId)
      .eq('cancer_type', cancerType)
      .single();

    if (error) throw error;
    return data as TxScore | null;
  }

  /**
   * Get all TxScores for a gene (across all cancer types)
   */
  async getTxScoresForGene(geneId: string): Promise<TxScore[]> {
    const { data, error } = await this.supabase
      .from('tx_txscore_cache')
      .select('*')
      .eq('gene_id', geneId)
      .order('tvs', { ascending: false });

    if (error) throw error;
    return (data || []) as TxScore[];
  }

  /**
   * Get top targets for a cancer type
   */
  async getTopTargets(
    cancerType: string,
    filters?: TxScoreFilters,
    options?: RankingOptions
  ): Promise<TxScore[]> {
    let query = this.supabase
      .from('tx_txscore_cache')
      .select('*')
      .eq('cancer_type', cancerType);

    // Apply filters
    if (filters) {
      if (filters.min_tvs !== undefined) {
        query = query.gte('tvs', filters.min_tvs);
      }
      if (filters.min_efficacy !== undefined) {
        query = query.gte('efficacy_score', filters.min_efficacy);
      }
      if (filters.min_safety !== undefined) {
        query = query.gte('safety_score', filters.min_safety);
      }
      if (filters.min_druggability !== undefined) {
        query = query.gte('druggability_score', filters.min_druggability);
      }
      if (filters.recommended_modality !== undefined) {
        query = query.eq(
          'modality_recommendation->>recommended_modality',
          filters.recommended_modality
        );
      }
      if (filters.gene_ids && filters.gene_ids.length > 0) {
        query = query.in('gene_id', filters.gene_ids);
      }
    }

    // Apply ordering
    const orderBy = options?.order_by || 'tvs';
    const orderDirection = options?.order_direction || 'desc';
    query = query.order(orderBy, { ascending: orderDirection === 'asc' });

    // Apply pagination
    if (options?.limit !== undefined) {
      query = query.limit(options.limit);
    }
    if (options?.offset !== undefined) {
      query = query.range(
        options.offset,
        options.offset + (options.limit || 100) - 1
      );
    }

    const { data, error } = await query;

    if (error) throw error;
    return (data || []) as TxScore[];
  }

  /**
   * Get pan-cancer targets (high TVS across multiple cancer types)
   */
  async getPanCancerTargets(
    minCancerTypes: number = 3,
    minTvs: number = 0.7
  ): Promise<Array<{ gene_id: string; cancer_types: string[]; avg_tvs: number }>> {
    const { data, error } = await this.supabase.rpc('get_pan_cancer_targets' as any, {
      p_min_cancer_types: minCancerTypes,
      p_min_tvs: minTvs,
    });

    if (error) throw error;
    return (data || []) as Array<{ gene_id: string; cancer_types: string[]; avg_tvs: number }>;
  }

  /**
   * Rank targets by composite criteria
   */
  async rankTargets(
    cancerType: string,
    weights: {
      efficacy?: number;
      safety?: number;
      druggability?: number;
      precedent?: number;
      stratification?: number;
    },
    limit: number = 100
  ): Promise<TxScore[]> {
    // Normalize weights to sum to 1
    const totalWeight = Object.values(weights).reduce((a, b) => a + b, 0);
    const normalizedWeights = Object.fromEntries(
      Object.entries(weights).map(([k, v]) => [k, v / totalWeight])
    );

    const { data, error } = await this.supabase.rpc('rank_targets_custom' as any, {
      p_cancer_type: cancerType,
      p_weights: normalizedWeights,
      p_limit: limit,
    });

    if (error) throw error;
    return (data || []) as TxScore[];
  }

  // ===================================================================
  // ADVANCED QUERIES
  // ===================================================================

  /**
   * Get comprehensive gene profile
   */
  async getGeneProfile(geneId: string, cancerType?: string) {
    const [
      gene,
      depmap,
      gtex,
      constraint,
      structure,
      clinvar,
      drugs,
      trials,
      txscores,
    ] = await Promise.all([
      this.getGene(geneId),
      this.getDepMapData(geneId, cancerType),
      this.getGTExExpression(geneId),
      this.getGnomADConstraint(geneId),
      this.getAlphaFoldStructure(geneId),
      this.getClinVarVariants(geneId),
      this.getDrugInteractions(geneId),
      this.getClinicalTrials(geneId),
      cancerType
        ? this.getTxScore(geneId, cancerType).then((d) => (d ? [d] : []))
        : this.getTxScoresForGene(geneId),
    ]);

    return {
      gene,
      depmap,
      gtex,
      constraint,
      structure,
      clinvar: {
        all: clinvar,
        pathogenic: clinvar.filter((v) =>
          ['Pathogenic', 'Likely pathogenic'].includes(v.clinical_significance)
        ),
      },
      drugs: {
        all: drugs,
        approved: drugs.filter((d) => d.approval_status === 'approved'),
      },
      trials: {
        all: trials,
        advanced: trials.filter((t) =>
          ['Phase 2', 'Phase 3', 'Phase 4'].includes(t.phase || '')
        ),
        failed: trials.filter(
          (t) =>
            ['Terminated', 'Withdrawn'].includes(t.status) &&
            ['Phase 2', 'Phase 3'].includes(t.phase || '')
        ),
      },
      txscores,
    };
  }

  /**
   * Compare genes side-by-side
   */
  async compareGenes(geneIds: string[], cancerType: string) {
    const profiles = await Promise.all(
      geneIds.map((id) => this.getGeneProfile(id, cancerType))
    );

    return profiles;
  }

  /**
   * Find similar targets (by TxScore profile)
   */
  async findSimilarTargets(
    geneId: string,
    cancerType: string,
    limit: number = 10
  ): Promise<TxScore[]> {
    const { data, error } = await this.supabase.rpc('find_similar_targets' as any, {
      p_gene_id: geneId,
      p_cancer_type: cancerType,
      p_limit: limit,
    });

    if (error) throw error;
    return (data || []) as TxScore[];
  }

  // ===================================================================
  // CACHE MANAGEMENT
  // ===================================================================

  /**
   * Compute and cache TxScore for a gene and cancer type
   */
  async computeAndCacheTxScore(
    geneId: string,
    cancerType: string,
    modelVersion: string = 'v1.0'
  ): Promise<TxScore> {
    const { data, error } = await this.supabase.rpc('compute_txscore' as any, {
      p_gene_id: geneId,
      p_cancer_type: cancerType,
      p_model_version: modelVersion,
    });

    if (error) throw error;
    return data as TxScore;
  }

  /**
   * Batch compute TxScores
   */
  async batchComputeTxScores(
    geneIds: string[],
    cancerTypes: string[],
    modelVersion: string = 'v1.0'
  ): Promise<TxScore[]> {
    const results: TxScore[] = [];

    for (const geneId of geneIds) {
      for (const cancerType of cancerTypes) {
        try {
          const score = await this.computeAndCacheTxScore(
            geneId,
            cancerType,
            modelVersion
          );
          results.push(score);
        } catch (err) {
          console.error(`Failed to compute TxScore for ${geneId} in ${cancerType}:`, err);
        }
      }
    }

    return results;
  }

  /**
   * Invalidate cache for a gene
   */
  async invalidateCache(geneId: string): Promise<void> {
    const { error } = await this.supabase
      .from('tx_txscore_cache')
      .delete()
      .eq('gene_id', geneId);

    if (error) throw error;
  }

  /**
   * Refresh stale cache entries
   */
  async refreshStaleCache(olderThanDays: number = 30): Promise<number> {
    const cutoffDate = new Date();
    cutoffDate.setDate(cutoffDate.getDate() - olderThanDays);

    const { data, error } = await this.supabase.rpc('refresh_stale_cache' as any, {
      p_cutoff_date: cutoffDate.toISOString(),
    });

    if (error) throw error;
    return (data as number) || 0;
  }

  // ===================================================================
  // ANALYTICS
  // ===================================================================

  /**
   * Get TxScore distribution for a cancer type
   */
  async getTxScoreDistribution(cancerType: string) {
    const { data, error } = await this.supabase.rpc('get_tvs_distribution' as any, {
      p_cancer_type: cancerType,
    });

    if (error) throw error;
    return data;
  }

  /**
   * Get subscore correlations
   */
  async getSubscoreCorrelations(cancerType?: string) {
    const { data, error } = await this.supabase.rpc('get_subscore_correlations' as any, {
      p_cancer_type: cancerType,
    });

    if (error) throw error;
    return data;
  }

  /**
   * Get protein class enrichment in top targets
   */
  async getProteinClassEnrichment(
    cancerType: string,
    topN: number = 100
  ) {
    const { data, error } = await this.supabase.rpc('get_protein_class_enrichment' as any, {
      p_cancer_type: cancerType,
      p_top_n: topN,
    });

    if (error) throw error;
    return data;
  }
}

// =====================================================================
// UTILITY FUNCTIONS
// =====================================================================

/**
 * Normalize Chronos effect to [0, 1]
 * More negative = more essential
 */
export function normalizeChronos(chronosEffect: number): number {
  const clamped = Math.max(Math.min(chronosEffect, 0), -2.5);
  return (0 - clamped) / (0 - -2.5);
}

/**
 * Classify LOEUF constraint
 */
export function classifyLOEUF(loeuf: number): string {
  if (loeuf < 0.35) return 'highly_constrained';
  if (loeuf < 0.6) return 'constrained';
  if (loeuf < 1.0) return 'moderate';
  return 'unconstrained';
}

/**
 * Classify pLI
 */
export function classifyPLI(pli: number): string {
  if (pli > 0.9) return 'LoF_intolerant';
  if (pli > 0.5) return 'intermediate';
  return 'LoF_tolerant';
}

/**
 * Classify structure quality
 */
export function classifyStructureQuality(plddt: number): string {
  if (plddt > 90) return 'very_high';
  if (plddt > 70) return 'confident';
  if (plddt > 50) return 'low';
  return 'very_low';
}

/**
 * Classify TVS
 */
export function classifyTVS(tvs: number): string {
  if (tvs > 0.8) return 'exceptional';
  if (tvs > 0.7) return 'high';
  if (tvs > 0.5) return 'moderate';
  if (tvs > 0.3) return 'low';
  return 'very_low';
}

/**
 * Get color for TVS visualization
 */
export function getTVSColor(tvs: number): string {
  if (tvs > 0.8) return '#10b981'; // green
  if (tvs > 0.7) return '#84cc16'; // lime
  if (tvs > 0.5) return '#eab308'; // yellow
  if (tvs > 0.3) return '#f97316'; // orange
  return '#ef4444'; // red
}

/**
 * Format TPM for display
 */
export function formatTPM(tpm: number): string {
  if (tpm < 1) return tpm.toFixed(2);
  if (tpm < 10) return tpm.toFixed(1);
  return Math.round(tpm).toString();
}

/**
 * Format p-value
 */
export function formatPValue(p: number): string {
  if (p < 0.0001) return 'p < 0.0001';
  if (p < 0.001) return `p = ${p.toFixed(4)}`;
  if (p < 0.01) return `p = ${p.toFixed(3)}`;
  return `p = ${p.toFixed(2)}`;
}

// =====================================================================
// EXPORT
// =====================================================================

export default TxScoreClient;
