"use client";
import { useEffect, useState } from "react";
import type { LabReceipt } from "@/lib/lab/evidence";
import { evidenceScenes, sceneSvg } from "@/lib/lab/figures";

const display = (value: number | null | undefined, fraction = false) => value == null ? "Not measured" : fraction ? `${(value * 100).toFixed(1)}%` : value.toPrecision(3);
export function RecordedLabEvidence({ records, downloadHref }: { records: LabReceipt[]; downloadHref: string }) {
  const individual = (hash: string, format: string, figure?: number) => `${downloadHref.replace(/&download=zip$/, "")}&receipt=${hash}&format=${format}${figure ? `&figure=${figure}` : ""}`;
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center gap-3"><h3 className="text-sm font-medium text-ink">Laboratory evidence</h3><a className="ml-auto text-xs text-cyan-700 underline" href={downloadHref}>Download all receipts, HTML, SVG, PDF and plot specifications</a></div>
    {records.map(record => <section key={`${record.sha256}:${record.comparison_id}`} className="space-y-3 rounded-lg border border-line p-3">
      <header><h4 className="text-sm font-medium capitalize text-ink">{record.kind === "context" ? "DepMap reference context" : record.kind === "drift" ? "Library and reagent diagnostics" : record.kind === "isoforms" ? "Isoform-aware guide mapping" : "Temporal kinetics"}</h4><p className="mt-1 text-xs leading-relaxed text-body">{record.payload.interpretation ?? record.payload.reason ?? record.payload.status}</p></header>
      {record.kind === "kinetics" && <>{record.payload.unmeasured_trajectories?.map(t => <p key={`${t.condition}:${t.replicate}`} className="text-xs text-muted">{t.condition} / {t.replicate}: {t.reason}</p>)}<p className="text-xs text-muted">{record.payload.normalization} normalization , pseudocount {record.payload.pseudocount} , {record.payload.n_guides} measured guides</p><div className="overflow-auto"><table className="w-full text-xs"><thead><tr>{["Condition", "Slope / day", "Biological trajectories", "95% interval"].map(h => <th key={h} className="p-2 text-left">{h}</th>)}</tr></thead><tbody>{record.payload.conditions?.map(c => <tr key={c.condition} className="border-t border-line"><td className="p-2">{c.condition}</td><td className="p-2">{display(c.slope)}</td><td className="p-2">{c.n_replicates}</td><td className="p-2">{c.ci95 ? `${display(c.ci95[0])} to ${display(c.ci95[1])}` : "Needs independent biological replication"}</td></tr>)}</tbody></table></div></>}
      {record.kind === "isoforms" && <><p className="text-xs text-muted">{record.payload.reference} , {record.payload.transcripts?.length ?? 0} transcripts. Exon numbers and strand are shown only when recorded in the annotation cache.</p><div className="overflow-auto"><table className="w-full text-left text-xs"><thead><tr>{["Guide", "Log2FC", "Coding transcripts", "Measured expression coverage"].map(h => <th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{record.payload.guides?.map(g => <tr key={g.guide_key} className="border-t border-line"><td className="p-2 font-mono">{g.guide_key}</td><td className="p-2">{display(g.lfc)}</td><td className="p-2">{g.annotation ? `${g.annotation.n_coding} / ${g.annotation.n_transcripts} (${display(g.annotation.coding_fraction, true)})` : g.reason ?? "Unresolved"}</td><td className="p-2">{g.expression ? <>{g.expression.status}: {display(g.expression.coding_fraction, true)}<p>{g.expression.source} , {g.expression.note}</p></> : "Transcript expression not supplied"}</td></tr>)}</tbody></table></div></>}
      {record.kind === "context" && <><p className="text-xs">Gene-effect release {record.payload.gene_effect_release ?? "unavailable"} , match {record.payload.match_tier ?? "none"} , lineage {record.payload.lineage ?? "unmatched"}</p><p className="text-xs">Relative copy number: {display(record.payload.copy_number?.value)} ({record.payload.copy_number?.release ?? "not recorded"}). {record.payload.copy_number?.scale}</p><p className="text-xs text-muted">Global fraction at effect ≤ −0.5: {display(record.payload.global_reference?.fraction_effect_le_minus_0_5, true)} of {record.payload.global_reference?.n_measured_models ?? 0} measured models.</p></>}
      {record.kind === "drift" && <>{record.payload.flags?.map(flag => <p key={`${flag.sample}:${flag.code}`} role="alert" className="rounded bg-amber-50 p-2 text-xs text-amber-900">{flag.sample}: {flag.message} Observed {(flag.value * 100).toFixed(1)}%.</p>)}<p className="text-xs">Library: {record.payload.library} , lot: {record.payload.reagent_lot ?? "Not recorded"}</p><dl className="grid grid-cols-2 gap-3 text-xs"><div><dt>Negative-control guides</dt><dd>{record.payload.negative_controls?.n_guides ?? 0} measured , LFC SD {display(record.payload.negative_controls?.sd_lfc)} , {record.payload.negative_controls?.status}</dd></div><div><dt>Core-essential guides</dt><dd>{record.payload.core_essential_guides?.n_guides ?? 0} measured , LFC SD {display(record.payload.core_essential_guides?.sd_lfc)} , {record.payload.core_essential_guides?.status} , within-gene LFC variance {display(record.payload.core_essential_guides?.within_gene_variance_lfc)} across {record.payload.core_essential_guides?.n_multiguide_genes ?? 0} genes</dd></div></dl><div className="overflow-auto"><table className="w-full text-xs"><thead><tr>{["Sample", "Role", "Raw-count Gini", "Zero guides"].map(h => <th className="p-2 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{record.payload.samples?.map(s => <tr className="border-t border-line" key={s.sample}><td className="p-2">{s.sample}</td><td className="p-2">{s.role ?? "Unknown"}</td><td className="p-2">{display(s.raw_count_gini)}</td><td className="p-2">{display(s.zero_fraction, true)}</td></tr>)}</tbody></table></div></>}
      {evidenceScenes(record).map((scene, i) => <div key={i} className="overflow-auto rounded border border-line bg-white"><div className="min-w-[650px] [&_svg]:h-auto [&_svg]:w-full" dangerouslySetInnerHTML={{ __html: sceneSvg(scene) }} /><div className="flex gap-4 p-2 text-xs text-cyan-700 underline">{["svg","pdf","spec"].map(format => <a key={format} href={individual(record.sha256,format,i+1)}>{format === "spec" ? "Plot specification" : format.toUpperCase()}</a>)}</div></div>)}
      <div className="flex gap-3 text-xs text-cyan-700 underline"><a href={individual(record.sha256,"receipt")}>Receipt JSON</a><a href={individual(record.sha256,"canonical")}>Original canonical bytes</a></div>
      <details className="text-xs text-muted"><summary>Receipt and exact measurements</summary><p className="mt-2 break-all font-mono">SHA-256: {record.sha256}</p><p>Comparison: {record.comparison_id ?? "Not recorded"} , recorded {record.recorded_at ?? "Not recorded"}</p><pre className="mt-2 max-h-80 overflow-auto whitespace-pre-wrap break-all rounded bg-canvas p-2">{JSON.stringify({ inputs: record.inputs, payload: record.payload }, null, 2)}</pre></details>
    </section>)}
  </div>;
}
export function LabEvidencePanel({ screenId, gene, runId, comparisonId }: { screenId: string; gene: string; runId?: string; comparisonId?: string }) {
  const [result, setResult] = useState<{ path: string; status: string; records?: LabReceipt[] } | null>(null);
  const params = new URLSearchParams(); if (runId) params.set("run", runId); if (comparisonId) params.set("comparison", comparisonId);
  const path = `/api/v1/screens/${screenId}/genes/${encodeURIComponent(gene)}/evidence?${params}`;
  useEffect(() => {
    const controller = new AbortController();
    fetch(path, { signal: controller.signal, cache: "no-store" }).then(async response => {
      const body = await response.json();
      if (!controller.signal.aborted) setResult(response.ok ? { ...body, path } : { path, status: "unavailable" });
    }).catch(() => { if (!controller.signal.aborted) setResult({ path, status: "unavailable" }); });
    return () => controller.abort();
  }, [path]);
  if (!result || result.path !== path) return <p role="status" className="text-xs text-muted">Reading recorded lab evidence…</p>;
  if (result.status !== "ready") return <section className="space-y-2 text-xs text-muted"><h3 className="font-medium text-ink">Laboratory evidence</h3><p>{result.status === "not_recorded" ? "This run has no recorded lab evidence for this gene. Enable the relevant module and run the analysis; missing evidence is not a negative finding." : "Lab evidence could not be read. Retry when the workspace database is available."}</p><a href={`/dashboard/memory?q=${encodeURIComponent(gene)}`} className="text-cyan-700 underline">Search this gene across the lab</a></section>;
  return <RecordedLabEvidence records={result.records ?? []} downloadHref={`${path}&download=zip`} />;
}
