import { NextResponse } from 'next/server';
import { getApiUser, supabaseAdmin } from '@/lib/supabase/server';
import type { CreateLabRequest, Lab } from '@/lib/types';

export const dynamic = 'force-dynamic';

/**
 * POST /api/labs/create
 * Create a new lab. User automatically becomes PI.
 *
 * Request body:
 * - name: string (required, 3-200 chars)
 * - department?: string (optional)
 * - institution?: string (optional)
 * - lab_website?: string (optional)
 *
 * Returns:
 * - lab: Lab object with generated invite_code
 * - membership: LabMember object for creator
 */
export async function POST(request: Request) {
  try {
    const { user, error: authError } = await getApiUser();
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const admin = supabaseAdmin as any;
    const body: CreateLabRequest = await request.json();
    const { name, department, institution, lab_website } = body;

    // ===== VALIDATION =====

    if (!name?.trim()) {
      return NextResponse.json(
        { error: 'Lab name is required' },
        { status: 400 }
      );
    }

    const trimmedName = name.trim();
    if (trimmedName.length < 3) {
      return NextResponse.json(
        { error: 'Lab name must be at least 3 characters' },
        { status: 400 }
      );
    }

    if (trimmedName.length > 200) {
      return NextResponse.json(
        { error: 'Lab name must be 200 characters or less' },
        { status: 400 }
      );
    }

    // Validate URL format if provided
    if (lab_website?.trim()) {
      try {
        new URL(lab_website.trim());
      } catch {
        return NextResponse.json(
          { error: 'Invalid lab website URL format' },
          { status: 400 }
        );
      }
    }

    // ===== CHECK IF USER ALREADY IN LAB =====

    const { data: existingMembership } = await admin
      .from('lab_members')
      .select('id, lab_id')
      .eq('user_id', user.id)
      .maybeSingle();

    if (existingMembership) {
      return NextResponse.json(
        {
          error: 'You are already a member of a lab. Leave your current lab before creating a new one.',
        },
        { status: 400 }
      );
    }

    // ===== CREATE LAB =====
    // Note: invite_code is automatically generated by database trigger

    const { data: lab, error: labError } = await admin
      .from('labs')
      .insert({
        name: trimmedName,
        pi_user_id: user.id,
        department: department?.trim() || null,
        institution: institution?.trim() || null,
        lab_website: lab_website?.trim() || null,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })
      .select()
      .single();

    if (labError) {
      console.error('Lab creation error:', labError);
      throw new Error(labError.message || 'Failed to create lab');
    }

    // ===== ADD CREATOR AS PI MEMBER =====

    const { data: membership, error: memberError } = await admin
      .from('lab_members')
      .insert({
        lab_id: lab.id,
        user_id: user.id,
        role: 'pi',
        title: 'Principal Investigator',
        joined_at: new Date().toISOString(),
      })
      .select()
      .single();

    if (memberError) {
      console.error('Member creation error:', memberError);
      // Rollback: Delete the lab we just created
      await admin.from('labs').delete().eq('id', lab.id);
      throw new Error('Failed to create lab membership');
    }

    // ===== SUCCESS RESPONSE =====

    return NextResponse.json({
      success: true,
      lab: lab as Lab,
      membership,
      message: `Lab "${lab.name}" created successfully! Your invite code is ${lab.invite_code}`,
    });
  } catch (error: any) {
    console.error('Create lab error:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to create lab' },
      { status: 500 }
    );
  }
}
